In [3]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [21]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
      self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probablities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
      
    self.output = probablities

X, y = spiral_data(100, 3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
activation1.forward(dense1.output)
print(activation1.output[:5],"\n\n")
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])

[[0.         0.         0.        ]
 [0.         0.00079887 0.00100914]
 [0.         0.         0.00218498]
 [0.         0.00061934 0.0035448 ]
 [0.         0.00025029 0.00476798]] 

[[0.33333334 0.33333334 0.33333334]
 [0.3333726  0.33329317 0.33333418]
 [0.33337    0.3332807  0.33334923]
 [0.33341014 0.3332357  0.3333541 ]
 [0.33342037 0.33321363 0.33336604]]


In [24]:
activation2.forward([[4,5,6, 7]])
activation2.output

array([[0.0320586 , 0.08714432, 0.23688282, 0.64391426]])

In [23]:
inputs2 = [[2, 3, 4, 5]]
activation2.forward(inputs2)
activation2.output

array([[0.0320586 , 0.08714432, 0.23688282, 0.64391426]])

In [ ]:
E = 2.718828
exp_values =

In [ ]:
exp_values = np.exp(inputs)