## Imports

In [3]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

## Dense layer class

In [10]:
class Layer_Dense:
    # layer initialization
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        self.weights = 0.01*np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    
    # forward pass
    def forward(self, inputs):
        # Calculate the output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

## Create dataset

In [11]:
x,y = spiral_data(samples=100, classes=3)

## Create dense layer with 2 input features and 3 output values

In [13]:
dense1 = Layer_Dense(2,3)

## Perform a forward pass of training data through this layer

In [15]:
dense1.forward(x)

## Check the output (first 5 samples)

In [18]:
print(dense1.output[:5])
print(dense1.weights)
print(dense1.biases)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-2.61496298e-05 -5.70940247e-05 -1.16960771e-04]
 [-7.69893813e-05 -4.75328154e-04 -2.12466970e-04]
 [-1.19454686e-04 -6.26299181e-04 -3.77396704e-04]
 [-1.59333722e-04 -8.86327529e-04 -4.81519091e-04]]
[[-0.00110489 -0.016607    0.00115148]
 [-0.00379148 -0.01742356 -0.01303243]]
[[0. 0. 0.]]


In [19]:
dense2 = Layer_Dense(3, 4)

In [20]:
print(dense2.weights)

[[ 0.0060512   0.00895556 -0.00131909  0.00404762]
 [ 0.00223844  0.00329623  0.01285984 -0.01506998]
 [ 0.00676461 -0.00382009 -0.00224259 -0.0030225 ]]


In [21]:
print(dense2.biases)

[[0. 0. 0. 0.]]


In [23]:
dense2.forward(dense1.output)

In [24]:
print(dense2.output)

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0772317e-06  2.4421036e-08 -4.3743145e-07  1.1080759e-06]
 [-2.9671253e-06 -1.4446309e-06 -5.5346122e-06  7.4937448e-06]
 ...
 [ 2.4684825e-05  6.4536514e-05  1.9644534e-04 -2.1663161e-04]
 [ 1.1826317e-04  7.9331898e-05  2.8289089e-04 -3.6258774e-04]
 [ 5.6686196e-05  7.4169009e-05  2.3910316e-04 -2.7997899e-04]]


In [25]:
dense3 = Layer_Dense(4, 2)

In [26]:
print(dense3.weights)

[[-3.7514709e-03 -1.2261962e-02]
 [ 1.8333918e-03  1.6709430e-02]
 [-5.6133018e-04 -1.3850427e-05]
 [-6.8729902e-03 -1.1747455e-03]]


In [27]:
print(dense3.biases)

[[0. 0.]]


In [28]:
dense3.forward(dense2.output)

In [ ]:
print(dense3.output)

In [30]:
output_layer = Layer_Dense(2, 1)

In [32]:
print(output_layer.weights, output_layer.biases)

[[ 0.00466166]
 [-0.00370242]] [[0.]]


In [34]:
output_layer.forward(dense3.output)
print(output_layer.output)

[[ 0.00000000e+00]
 [-6.09291922e-11]
 [-1.99093450e-10]
 [-3.01775049e-10]
 [-4.05787959e-10]
 [-3.91383703e-10]
 [-5.79444603e-10]
 [-7.10176862e-10]
 [-7.84134202e-10]
 [-7.52647611e-10]
 [-8.17014789e-10]
 [-9.12637799e-10]
 [-8.24378510e-10]
 [-8.14549372e-10]
 [-1.08640075e-09]
 [-1.10905418e-09]
 [-2.77338541e-10]
 [-1.04850129e-09]
 [-1.15630316e-09]
 [-3.11040499e-10]
 [ 3.30090157e-11]
 [ 2.06638440e-09]
 [-1.23217478e-10]
 [ 1.78329629e-09]
 [ 1.86549376e-09]
 [ 1.44047682e-11]
 [ 2.33622455e-09]
 [ 5.71689307e-10]
 [-1.17500898e-09]
 [ 2.84087709e-09]
 [ 6.85797252e-10]
 [ 3.11492987e-09]
 [ 2.66941180e-09]
 [ 2.63021183e-09]
 [ 3.07141490e-09]
 [ 3.48909834e-09]
 [ 3.57729002e-09]
 [ 3.50602902e-09]
 [ 3.82688103e-09]
 [ 3.77637610e-09]
 [ 3.79521570e-09]
 [ 3.11682813e-09]
 [ 2.17266738e-09]
 [ 2.27457675e-09]
 [ 3.76698495e-09]
 [ 4.31844471e-09]
 [-1.20904231e-09]
 [ 2.93860847e-09]
 [ 2.52209986e-09]
 [ 1.83388771e-09]
 [ 4.08999457e-09]
 [ 7.94582067e-10]
 [ 2.8474755

In [ ]:
print