In [1]:
import numpy as np

In [17]:
class Neuron_Layer:
    def __init__(self, inputs, weights, biases=0):      
        self.output = inputs@weights.T + biases
        print(self.output)

In [18]:
# inputs layer

In [19]:
inputs1 = np.array([
    [8, 3, 9],
    [9, 4, 2],
    [4, 7, 4]
])
weights1 = np.array([
    [0.5, 0.2, 0.4],
    [0.3, 0.8, 0.4], 
    [0.1, 0.8, 0.9],
    [0.3, 0.7, 0.1]
])
biases1 = np.array([0.2, 0.5, 0.3, 0.3])

In [24]:
layer1 = Neuron_Layer(inputs1, weights1, biases1)

[[ 8.4  8.9 11.6  5.7]
 [ 6.3  7.2  6.2  6. ]
 [ 5.2  8.9  9.9  6.8]]


In [25]:
inputs2 = layer1.output
weights2 = np.array([
    [0.1, 0.2, 0.8, 0.4],
    [0.6, 0.7, 0.4, 0.3],
    [0.1, 0.2, 0.8, 0.7]
])
biases2 = ([0.6, 0.9, 0.8])

In [26]:
layer2 = Neuron_Layer(inputs2, weights2, biases2)

[[14.78 18.52 16.69]
 [10.03 14.   12.03]
 [13.54 16.25 15.78]]


In [27]:
inputs3 = layer2.output
output_weight = np.array([
    [0.5, 0.8, 0.6],
    [0.2, 0.1, 0.7]
])

In [29]:
output_layer = Neuron_Layer(inputs3, output_weight)

[[32.22  16.491]
 [23.433 11.827]
 [29.238 15.379]]
