# Calculating Loss

### With a collection of softmax outputs and their intended targets, we can map these indices to retrieve the values from the softmax distributions:

In [1]:
softmax_outputs = [[0.7,0.1,0.2],
                   [0.1,0.5,0.4],
                   [0.02, 0.9, 0.08]]
class_targets = [0,1,1]

In [3]:
for targ_idx, distribution in zip(class_targets, softmax_outputs):
    print(distribution[targ_idx])

0.7
0.5
0.9


#### This can be further simplified using NumPy

In [8]:
import numpy as np

In [9]:
softmax_outputs = np.array([[0.7,0.1,0.2],
                   [0.1,0.5,0.4],
                   [0.02, 0.9, 0.08]])
class_targets = [0,1,1]

In [10]:
print(softmax_outputs[[0,1,2],class_targets])

[0.7 0.5 0.9]


#### We know we’re going to have as many indices as distributions in our entire batch, so we can use a ` range() ` instead of typing each value ourselves:

In [11]:
pred_confidences = softmax_outputs[range(len(softmax_outputs)), class_targets]

In [12]:
print(pred_confidences)

[0.7 0.5 0.9]


##### This returns a list of the confidences at the target indices for each of the samples. Now we apply the negative log to this list:

In [14]:
print(-np.log(pred_confidences))

[0.35667494 0.69314718 0.10536052]


##### NumPy has a method that computes this average on arrays, so we will use that to have an idea about how our model is doing during training

In [15]:
average_loss =np.mean(-np.log(pred_confidences))
print(average_loss)

0.38506088005216804


#### We have to add a test to the code we just wrote for the number of dimensions, move calculations of the log values outside of this new if statement, and implement the solution for the one-hot encoded labels following the first equation: 

In [16]:
class_targets = np.array([[1,0,0],
                          [0,1,0],
                          [0,1,0]])

In [17]:
# Probabilities for target values
# only if categorical labels
if len(class_targets.shape) == 1:
    print("Class targets shape: ", len(class_targets.shape))
    correct_confidences = softmax_outputs[
        range(len(softmax_outputs)),
        class_targets
    ]
    

# Mask values - only for one-hot encoded labels
elif len(class_targets.shape) == 2:
    print("Class targets shape: ", len(class_targets.shape))
    corrent_confidences = np.sum(
        softmax_outputs*class_targets, axis=1)

Class targets shape:  2


In [19]:
# Losses
neg_log = -np.log(corrent_confidences)

In [20]:
average_loss = np.mean(neg_log)
print(average_loss)

0.38506088005216804
