In [2]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [3]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
      self.output = np.dot(inputs, self.weights) + self.biases

class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probablities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
      
    self.output = probablities

X, y = spiral_data(100, 3)

dense1 = Layer_Dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_Dense(3, 3)
activation2 = Activation_Softmax()

dense1.forward(X)
print(dense1.output[:5])
activation1.forward(dense1.output)
print(activation1.output[:5],"\n\n")
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])

[[ 0.          0.          0.        ]
 [-0.00104752  0.00113954 -0.00047984]
 [-0.00274148  0.00317292 -0.00086922]
 [-0.00421884  0.00526663 -0.00055913]
 [-0.00577077  0.00714014 -0.0008943 ]]
[[0.         0.         0.        ]
 [0.         0.00113954 0.        ]
 [0.         0.00317292 0.        ]
 [0.         0.00526663 0.        ]
 [0.         0.00714014 0.        ]] 


[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [47]:
activation2.forward([[4,5,6, 7]])
activation2.output

array([[0.0320586 , 0.08714432, 0.23688282, 0.64391426]])

In [48]:
inputs2 = [[2, 3, 4, 5]]
activation2.forward(inputs2)
activation2.output

array([[0.0320586 , 0.08714432, 0.23688282, 0.64391426]])

In [50]:
exp_values = np.exp(inputs)

In [51]:
print(exp_values)

[  54.59815003  148.4131591   403.42879349 1096.63315843]


In [81]:
# Write code to comute the softmax scores for the following array
py_array = [4.5, 6.2, 5.5, 29]
np_array = np.array(py_array)
np_array_4 = np_array -  4
print(np_array)

[ 4.5  6.2  5.5 29. ]


In [82]:
np_array_expo = np.exp(np_array_4)

In [83]:
print(np_array_expo)

[1.64872127e+00 9.02501350e+00 4.48168907e+00 7.20048993e+10]


In [84]:
n_a_exp_sum = np.sum(np_array_expo)

In [85]:
print(n_a_exp_sum)

72004899352.5413


In [86]:
x = np_array_expo/n_a_exp_sum

In [87]:
print(x)

[2.28973485e-11 1.25338881e-10 6.22414462e-11 1.00000000e+00]


In [88]:
sum_x = np.sum(x)
print(sum_x)

0.9999999999999999


In [89]:
# [2.28973485e-11 1.25338881e-10 6.22414462e-11 1.00000000e+00]