# Learning Numpy

## Creating Arrays

In [1]:
# import numpy
import numpy as np

In [4]:
# creating a numpy array

array1 = np.array([10,20,30])

print(array1)

[10 20 30]


In [6]:
# creating a 1-D array 

array2 = np.array([5,-7.4, 'a', 7.2])

print(array2)

# Observe that since there is a string value in the list, 
# all integer and float values have been promoted to 
# string, while converting the list to array.

['5' '-7.4' 'a' '7.2']


In [7]:
# creatin a 2-D array

array3 = np.array([[2.4,3], [4.91, 7], [0, -1]])

print(array3)

[[ 2.4   3.  ]
 [ 4.91  7.  ]
 [ 0.   -1.  ]]


## Slicing Arrays

In [18]:
# Define which part of the array to be sliced by specifying
# the start and end index values using [start : end] along
# with the array name

array1 = np.array([-2, 2, 6, 10, 14, 18, 22])
sliced_array1 = array1[3:5]
print(sliced_array1)


# reverse the array
sliced_array1 = array1[::-1]
print(sliced_array1)

[10 14]
[22 18 14 10  6  2 -2]


### Slicing 2-D arrays

In [21]:
first2dArray = np.array([[7,0,10,20], [-5,1,40,200], [-1,1,4,30]])
print(first2dArray)

[[  7   0  10  20]
 [ -5   1  40 200]
 [ -1   1   4  30]]


In [22]:
# Access all the elements in the 3rd column
print(first2dArray[0:3,2])

[10 40  4]


In [23]:
# access elements of the 2nd and 3rd row from 1st and 
# 2nd column
print(first2dArray[1:3, 0:2])

[[-5  1]
 [-1  1]]


In [31]:
# If row indices are not specified, it means all the 
# rows are to be considered. Likewise, if column
# indices are not specified, all the columns are to 
# be considered.

print(first2dArray[1])

[ -5   1  40 200]


## Numpy Append

In [32]:
# To add a new row to an existing array, ensure that the 
# number of columns matches that of the existing array

newRow2dArray = np.append(first2dArray, [[2,7,8,2]], axis=0)
print(newRow2dArray)

[[  7   0  10  20]
 [ -5   1  40 200]
 [ -1   1   4  30]
 [  2   7   8   2]]


In [33]:
# To add a new column to an existing array, ensure that the 
# number of rows matches that of the existing array

newColumnArray = np.append(first2dArray, [[2], [7], [8]], axis = 1)
print(newColumnArray)

[[  7   0  10  20   2]
 [ -5   1  40 200   7]
 [ -1   1   4  30   8]]


## Numpy Sort

In [35]:

array4 = np.array([3234,23,63,64,93,3])
array4_sorted = np.sort(array4)

print(array4_sorted)

[   3   23   63   64   93 3234]


In [36]:
# to sort in descending order, we use the reverse slicing [::-1]
array4_sorted_reversed = np.sort(array4)[::-1]

print(array4_sorted_reversed)

[3234   93   64   63   23    3]


## Reshaping Arrays