In [1]:
import numpy as np

In [2]:
inputs = [
    [8, 3, 9],
    [9, 4, 2],
    [4, 7, 4]
]

layer1_weights = [
    [0.5, 0.2, 0.4],
    [0.3, 0.8, 0.4], 
    [0.1, 0.8, 0.9],
    [0.3, 0.7, 0.1]
]
layer1_biases = [0.2, 0.5, 0.3, 0.3]

In [3]:
layer2_weights = [
    [0.1, 0.2, 0.8, 0.4],
    [0.6, 0.7, 0.4, 0.3],
    [0.1, 0.2, 0.8, 0.7]
]

layer2_biases = [0.6, 0.9, 0.8]

In [4]:
output_layer_weights = [
    [0.5, 0.8, 0.6],
    [0.2, 0.1, 0.7]
]

In [5]:
layer1_outputs = np.dot(inputs, np.array(layer1_weights).T) + layer1_biases
print(layer1_outputs)

[[ 8.4  8.9 11.6  5.7]
 [ 6.3  7.2  6.2  6. ]
 [ 5.2  8.9  9.9  6.8]]


In [6]:
layer2_outputs = np.dot(layer1_outputs, np.array(layer2_weights).T) + layer2_biases
print(layer2_outputs)

[[14.78 18.52 16.69]
 [10.03 14.   12.03]
 [13.54 16.25 15.78]]


In [7]:
output = np.dot(layer2_outputs, np.array(output_layer_weights).T)
print(output)

[[32.22  16.491]
 [23.433 11.827]
 [29.238 15.379]]


In [16]:
layer_1_outputs = np.matmul(np.array(inputs), np.array(layer1_weights).T) + np.array(layer1_biases)
print(layer_1_outputs)

[[ 8.4  8.9 11.6  5.7]
 [ 6.3  7.2  6.2  6. ]
 [ 5.2  8.9  9.9  6.8]]


In [17]:
layer_2_outputs = np.matmul(np.array(layer_1_outputs), np.array(layer2_weights).T) + np.array(layer2_biases)
print(layer_2_outputs)

[[14.78 18.52 16.69]
 [10.03 14.   12.03]
 [13.54 16.25 15.78]]


In [19]:
outputs = np.matmul(np.array(layer_2_outputs), np.array(output_layer_weights).T)
print(outputs)

[[32.22  16.491]
 [23.433 11.827]
 [29.238 15.379]]


In [20]:
print(output == outputs)

[[ True  True]
 [ True  True]
 [ True  True]]


In [21]:
layer_11_outputs = (np.array(inputs) @ np.array(layer1_weights).T) + np.array(layer1_biases)
print(layer_11_outputs)

[[ 8.4  8.9 11.6  5.7]
 [ 6.3  7.2  6.2  6. ]
 [ 5.2  8.9  9.9  6.8]]


In [23]:
layer_22_outputs = (np.array(layer_1_outputs) @ np.array(layer2_weights).T) + np.array(layer2_biases)
print(layer_22_outputs)

[[14.78 18.52 16.69]
 [10.03 14.   12.03]
 [13.54 16.25 15.78]]


In [24]:
output = (layer2_outputs @ np.array(output_layer_weights).T)
print(output)

[[32.22  16.491]
 [23.433 11.827]
 [29.238 15.379]]
